Brightness Control
profi200/open_agb_firm pull request #74
Opened 2022-06-23 03:40 UTC by spitzeqc

Added controls for adjusting display brightness in game.

Partially fulfills #58. It does not use the 3ds slider, but rather the X button along with UP/DOWN buttons to make it compatible with 2ds as well. Additionally, screen can be completely turned off with X+LEFT, and turned back on X+RIGHT. 

While this implementation is limited (screen brightness is reset to ini value after reset) and a bit clunky (game still registers d-pad presses, and controls are not necessarily intuitive), it does allow for users to change brightness without restarting the console

2022-06-24 10:27 UTC, profi200 commented
I will take a look later. Thanks.

2022-06-26 18:06 UTC, profi200 requested changes
Sorry, didn't see the review was still pending.

2022-06-27 05:48 UTC, spitzeqc commented
Adjustments have been made. Turning on and off display have been switched to using GFX_powerOffBacklight() and GFX_powerOnBacklight(). Additionally, all brightness related controls have been put into its own function which is called from 'main' instead of 'gbaGfxHandler'. 

One thing that still needs to be tested is turning on and off the display(s) on an o2ds. Currently, power related functions are called on GFX_BLIGHT_TOP and GFX_BLIGHT_BOTH for release and non-release (debug?) versions respectively. I lack the proper hardware to test if this will cause issues on the o2ds as it only contains one panel.

2022-06-27 22:40 UTC, profi200 approved these changes

2022-06-27 22:41 UTC, merged